# Use Python 3.10
FROM python:3.10-slim

# Working Directory
WORKDIR /app

# Install System Deps (SimPy might need build tools sometimes, but usually pure python)
RUN apt-get update && apt-get install -y gcc

# Copy Requirements
COPY requirements.txt .
# Install Requirements
RUN pip install --no-cache-dir -r requirements.txt

# Copy Code
COPY backend/ backend/

# Expose Port
EXPOSE 8000

# Run Command
CMD ["uvicorn", "backend.src.api:app", "--host", "0.0.0.0", "--port", "8000"]
